name: Check package.json version
description: Check version in package.json

outputs:
    version:
        description: Version in package.json
        value: ${{ steps.check-version.outputs.version }}

runs:
    using: composite
    steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Check version
          id: check-version
          shell: bash
          run: bash ${{ github.action_path }}/scripts/check-version.sh
