name: Check package.json version
description: Check version in package.json
outputs:
  version:
    description: Version in package.json
    value: ${{ steps.check-version.outputs.version }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check version
      id: check-version
      shell: bash
      run: |
        PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version)
        CURRENT_VERSION=$(jq -r .version package.json)
        if [[ "$PREVIOUS_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "version="
        else
            echo "version=$CURRENT_VERSION"
        fi >> $GITHUB_OUTPUT
