name: Setup pnpm
description: Setting up pnpm and install dependencies
inputs:
  node-version:
    description: Node.js version to use
    required: true
    default: "20"
  npm-registry:
    description: NPM registry to use
    required: false
    default: "https://registry.npmjs.org/"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        registry-url: ${{ inputs.npm-registry }}
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      id: pnpm-cache
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      shell: bash
