name: Test check-version Action

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-update:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                version: [major, minor, patch]
                include:
                    - version: major
                      expected: 2.0.0
                    - version: minor
                      expected: 1.1.0
                    - version: patch
                      expected: 1.0.1

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Create a dummy package.json
              run: |
                  echo '{ "name": "dummy", "version": "1.0.0" }' > package.json
                  git add package.json
                  git commit -m "Add package.json"

            - name: Bump version to simulate change
              run: |
                  echo '{ "name": "dummy", "version": "${{ matrix.expected }}" }' > package.json
                  git add package.json
                  git commit -m "Bump version"

            - name: Test Check package.json version
              uses: ./check-version
              id: check-version

            - name: Assert version
              run: |
                  echo "Expected: ${{ matrix.expected }}"
                  echo "Actual: ${{ steps.check-version.outputs.version }}"

                  if [ "${{ matrix.expected }}" != "${{ steps.check-version.outputs.version }}" ]; then
                      echo "Version mismatch"
                      exit 1
                  fi
